# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RxSwift-Login-Validation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'RxSwift-Login-ValidationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwift-Login-ValidationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
